### ISSUE TITLE
Information for Users on How to Use the App

### ISSUE THREAD

**Issue by jhadakt** [SCCapstone/World-Watchlist#92]
No prompts, tutorial, or text boxes indicating what you can do or how to use the site on the Web browser. Just confusing to understand where to go, what different buttons do, and what actions will cause what. Could benefit from some sort of tutorial, or an introduction for first-time users.

**Comment by zhymirt** [comment]
The app allows for safe exploration and provides reactions for every button click. Tutorial could be helpful, but experimentation would be more time efficient
