### ISSUE TITLE
Accepting Friend Request Crashes App

### ISSUE THREAD

**Issue by jhadakt** [SCCapstone/World-Watchlist#96]
When click to add a friend from the pending friends for approval the app crashes. Error displayed in the photo below.![IMG_2169](https://user-images.githubusercontent.com/70026453/115084187-7e0e7a00-9ed6-11eb-94e1-b3bc2fed7693.JPG)

**Comment by justinelijahtaylor** [comment]
This bug occurs when you have two separate users signed into the app through two different tabs in the same browser. Since our final release will be a .apk file and not a website, there is no reason to fix.
